### ISSUE TITLE
"Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: Ana06/get-changed-files@v1.2" + "The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files."

### ISSUE THREAD

**Issue by janpio** [Ana06/get-changed-files#35]
When using this action, you now get these two error messages:
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/183673/228881129-ebaf3c0c-3b75-4bdf-8475-196b39686996.png">

Via https://github.com/jitterbit/get-changed-files/issues/65 it seems that https://github.com/masesgroup/retrieve-changed-files updated the original action to make these go away - so maybe this here can be "rebased" on that one.

**Comment by IuliaCMoldovan** [comment]
Hi,

I experienced the same issue.
@Ana06, will it be updated? If not, could you please let us know?

Thank you very much,
Iulia

**Comment by Ana06** [comment]
This was fixed in https://github.com/Ana06/get-changed-files/pull/20 and https://github.com/Ana06/get-changed-files/pull/21. Ensure you are using the last version: Ana06/get-changed-files@v2.2.0
